### ISSUE TITLE
multiple editors on a single page

### ISSUE THREAD

**Issue by z1haze** [w8tcha/CKEditor-WordCount-Plugin#100]
how could i have multiple editors on a single page but have different character/word limits for each

**Comment by w8tcha** [comment]
You would need a different config for each editor instance.

**Comment by z1haze** [comment]
can you device a better solution for this.. maybe be able to pass it in as options when creating it in the dom





 ---- On Sat, 17 Oct 2015 18:33:51 -0400 Ingo &lt;notifications@github.com&gt; wrote ----




You would need a different config for each editor instance.
