### ISSUE TITLE
Incorrect error when pasting text

### ISSUE THREAD

**Issue by emont01** [w8tcha/CKEditor-WordCount-Plugin#102]
![screen-shot_002](https://cloud.githubusercontent.com/assets/588937/10944640/3c001d90-82e8-11e5-9511-88e3cda5d6d8.png)

I am trying to limit the number or characters that a user can enter into a description field, but if I try to paste a text I am getting an error that says that the "content can not be pasted" because is too long, no matter the actual length of the mentioned text.

After checking the code I figured the actual problem is that the word validation is enforced even if it is disabled:

```javascript
// plugin.js file, from line 367 to 370
                if (wordCount > config.maxWordCount) {
                    notification.show();
                    event.cancel();
                }
```

I am using the jquery adapter and my textarea field is configured as follows:
```javascript
$('textarea.rich-text-editor').ckeditor({
    extraPlugins: 'wordcount',
    wordcount: {
        showParagraphs: false,
        showWordCount: false,
        showCharCount: true,
        maxWordCount: -1, //unlimited
        maxCharCount: 500
    }
});
```

**Comment by w8tcha** [comment]
This issue should be already fixed
