### ISSUE TITLE
The plugin is not compatible with ckeditor 4.5.4

### ISSUE THREAD

**Issue by aalaman** [w8tcha/CKEditor-WordCount-Plugin#104]
Very good work on the plugin but unfortunately tested it on ckeditor 4.5.4 (latest) and appears that the plugin has compatibility issues. The editor crashed immediately when adding the wordcount extension in the config, followed the same procedure as explained in the readme. With the extension loaded, the result was a blank box without ckeditor in the place where the editor was supposed to be visible, didn't check the error console on crome for the js error that it was causing. 

Tried the same setup with older ckeditor 4.4.8, worked out of the box.

**Comment by w8tcha** [comment]
Please check the browser error console.

**Comment by w8tcha** [comment]
Did you add the notification plugin to your editor? this is now required

**Comment by sirtet** [comment]
Ran into this too, adding the notifications plugin fixed it.
Can't plugins declare their dependencies somehow, so they fail gracefully?
If there's no infrastructure for that from CKEDITOR, could the plugin do the check itself?

**Comment by w8tcha** [comment]
No  there is no other solution
