### ISSUE TITLE
Default settings have changed?

### ISSUE THREAD

**Issue by sirtet** [w8tcha/CKEditor-WordCount-Plugin#107]
I updated to a newer version, and now i have paragraphs and words count, where before i had chars and words.
I'm not aware that i did set anything, so i guess it's changed defaults.

There would be two issues with that:
1. Changing defaults is bad for existing installs, why was it done? Could it be reverted?
2. Counting paragraphs instead of Chars seems not the most typical use case for me. Am i wrong?

**Comment by w8tcha** [comment]
Yes the default settings have been changed, but you still can enable chars count, and disable paragrahps count.

**Comment by sirtet** [comment]
Yes i understand.
Why did you do that?
It will have the bad side effect that people who upgrade also have to change the settings to get what they had. For new installs, that's not a problem
And also, i would say much more users are interested in char-count than paragraphs, so i wonder why this default was changed...
I don't complain, i just want to point out what i learned on other cases, that it's best practice to try add new features in a way that existing ones are not interfered.
(For me, i DO have a problem to adjust the settings, as the integration in Drupal seems not to work completely, so i depend on the defaults. But that's not a real reason to change anything back.)

**Comment by w8tcha** [comment]
Well you are the first one who noticed that, i think nobody complained before because most people simply fork the plugin to create there on defaults.
