### ISSUE TITLE
Suggestion for a pt.js file

### ISSUE THREAD

**Issue by cebola2** [w8tcha/CKEditor-WordCount-Plugin#112]
Language directory does not contain a pt.js file. pt-br.js seems incomplete. The following has worked for me as pt.js

CKEDITOR.plugins.setLang('wordcount', 'pt', {
    WordCount: 'Palavras:',
    CharCount: 'Caracteres:',
    CharCountWithHTML: 'Caracteres (incluindo HTML):',
    Paragraphs: 'Parágrafos:',
    pasteWarning: 'Conteúdo não pode ser colado porque ultrapassa o limite permitido',
    Selected: 'Seleccionado: ',
    title: 'Estatísticas'
});

**Comment by bigs21** [comment]
I've created a pull request for that, also updating the pt-br translation.
But I've translated to pt with the new "Orthographic Agreement" (Acordo Ortográfico).

**Comment by cebola2** [comment]
The only word that you might wonder about with respect to the Orthographic Agreement (AO90) is "caracteres" vs. "carateres". It happens that, as the second "c" in the first form is pronounced by a large part of the population in Portugal, both forms are admissible according to AO90 (yes, sometimes it is an agreement to disagree!). But, as Portuguese speaking countries in Africa have not adopted the AO90, you probably should stick with "caracteres".

**Comment by bigs21** [comment]
I don't totally agree when you say "It happens that, as the second "c" in the first form is pronounced by a large part of the population in Portugal", but you have valid arguments. Done!
Also, in the pasteWarning, replaced "Conteúdo..." by "O conteúdo..."

**Comment by w8tcha** [comment]
Can this issue be closed no wit the merge of the pull request?

**Comment by bigs21** [comment]
@w8tcha, yes it can
