### ISSUE TITLE
Notification not rendering properly

### ISSUE THREAD

**Issue by martinezrw** [w8tcha/CKEditor-WordCount-Plugin#116]
When you reach the maximum char count the notification is appearing but is not put into the colored box. Not sure if its a notification bug or wordcount.

![failednotify](https://cloud.githubusercontent.com/assets/13893628/12633533/deb071f0-c52f-11e5-94bb-59952c436224.jpg)

**Comment by w8tcha** [comment]
The problem is that the editor skin you are using is not compatible with the latest version of the editor. The notification boxes are styled by the skin.
