### ISSUE TITLE
Can add one more character after copy-pate

### ISSUE THREAD

**Issue by mims92** [w8tcha/CKEditor-WordCount-Plugin#121]
I'm using CKEDITOR 4.5.6 with wordcount plugin.

When I copy-paste a text in the CKeditor, the limit is reached, so it's ok.
But then, I can add one single character and it's also ok.
When inserting mutli characters, the wordcount plugin removes them.

It's like the `change` event is not triggered after a copy-paste.

It can be reproduced here: http://w8tcha.github.io/CKEditor-WordCount-Plugin/
1. Copy-paste text with max length
2. add one character -> you are above the limit

**Comment by aerionTech** [comment]
Has there been any progress on this issue?

**Comment by mims92** [comment]
Sadly no

**Comment by w8tcha** [comment]
Sorry but i no can reproduce the problem at the moment
