### ISSUE TITLE
Wrong word count with filter

### ISSUE THREAD

**Issue by vdeygas** [w8tcha/CKEditor-WordCount-Plugin#123]
Hi,

When I add a filter to remove an element before counting, word count return wrong results in case of several paragraphs.
It appears that last word of paragraph 1 is concatenated with first word of paragraph 2.
And it seems that this is due to htmlParser filter that remove line breaks beetween paragraphs.

With no filter spécified in config, no problem.

This can be reproduced with your sample page wordcountWithMaxCount.html and config :

```
filter: new CKEDITOR.htmlParser.filter({
                elements: {
                    span: function( element ) {
                        if(element.attributes.class == 'marker') {
                            return false;
                        }
                    }
                }
            })
```

Thanks,

**Comment by w8tcha** [comment]
Is this still an issue? I added the filter to the config and did some tests but at the moment it always shows the correct count!

Can you provide the editor content? Please re-open the issue if the issue is still occuring!
