### ISSUE TITLE
wordcount.css added multiple times

### ISSUE THREAD

**Issue by Luongatoolz** [w8tcha/CKEditor-WordCount-Plugin#125]
I've discovered wordcount.css being added multiple times to the <head> due to multiple instances of ckeditor on a single page. I've found that moving that line to onload method of plugin definition resolves the issue.

moving below line from init to onload of plugin definition:

`if (config.loadCss === undefined || config.loadCss) {
          CKEDITOR.document.appendStyleSheet(this.path + "css/wordcount.css");
        }`

**Comment by w8tcha** [comment]
Can you make a pull request for that?
