### ISSUE TITLE
config.wordcount {...} has no effect in config.js

### ISSUE THREAD

**Issue by FfdE** [w8tcha/CKEditor-WordCount-Plugin#126]
and config.wordcount {...} cannot be added to the individual editor on page itself either (editor does not appear then)... but its useless for me without the possibility to count on each editor differently... What am I doing wrong?

**Comment by w8tcha** [comment]
It depends how you load the editor on the page normally you need one config for each instance

**Comment by FfdE** [comment]
Thanx. Yes, thats what I did. I did the same with the plugin charcount and it worked there. So I gave it up with wordcount :( sorry.

**Comment by w8tcha** [comment]
Can you post the config where the editor don't show up`?
