### ISSUE TITLE
Not working in IE Edge

### ISSUE THREAD

**Issue by tania2** [w8tcha/CKEditor-WordCount-Plugin#130]
Hi all,
In IE Edge, i am getting the following error Unable to get property 'Paragraphs' of undefined or null reference after i installed this plugin.

**Comment by w8tcha** [comment]
Which language in the editor you are using?

**Comment by tania2** [comment]
Greek an english. Please have in mind that i have installed all the languages inckeditor.
Thanks in advanced.

**Comment by w8tcha** [comment]
at least with the latest version i can not reproduce the problem. the only explanation is that the language file for the plugin is missing.
