### ISSUE TITLE
Feature Request - Allow limiting line breaks

### ISSUE THREAD

**Issue by strohhut** [w8tcha/CKEditor-WordCount-Plugin#136]
Limiting the number of characters and spaces is not enough if you want to avoid that user posts take up huge space.

The following image has only two characters but eight lines.

![temp](https://cloud.githubusercontent.com/assets/15095059/18419087/f514dfe4-7853-11e6-9b73-c7523da5cbf9.JPG)

I think it would be nice to add a line count and line limit.

And BTW please fix not mentioning `htmlwriter` as a requirement on the Github readme and the documentation at http://ckeditor.com/addon/htmlwriter.

**Comment by hakeemM** [comment]
i need this feature.

**Comment by hakeemM** [comment]
replace line #162 plugin.js replace(/(\r\n|\n|\r)/gm, ""). with
replace(/()/gm, "") and it will count "enter key" in counter.

**Comment by w8tcha** [comment]
added this feature as setting in the latest commit
