### ISSUE TITLE
JS Error when maxCharCount value given

### ISSUE THREAD

**Issue by haideraliarain** [w8tcha/CKEditor-WordCount-Plugin#138]
Browser: IE11/chrome

Code:
var editor =  
		CKEDITOR.replace
		( 
			'additionalDetail', 
			{
    			customConfig: 'config.js'
    			,extraPlugins:'undo,htmlwriter,wordcount, notification'
    			,toolbar: [['Bold','Italic','-','OrderedList','UnorderedList','-','Link','Unlink','-','Source']]
				,width: '300px'
	    		,height: '270px'
	    		,wordcount:{showParagraphs: false,showWordCount: false,showCharCount: true,countSpacesAsChars: true,maxCharCount:400}
			}
		);

If i paste on editor it gives following error and if i remove maxCharCount from config paste works fine.
ERROR:
Error: Object doesn't support property or method 'getUniqueId'

**Comment by w8tcha** [comment]
What version of the CKEditor you are using? at least with the latest version i can not reproduce the issue.

**Comment by haideraliarain** [comment]
CKEditor Version : 4.3.1

**Comment by w8tcha** [comment]
Be aware that for the plugin you need CKEditor 4.5.x
