### ISSUE TITLE
When max chars count is reached, cursor jumps to content first position.

### ISSUE THREAD

**Issue by citius** [w8tcha/CKEditor-WordCount-Plugin#144]
You can reproduce this issue on [plugins demo page](http://w8tcha.github.io/CKEditor-WordCount-Plugin/) in Google Chrome 58 or Mozilla Firefox 52

Current behavior: 
 - in rich text mode (not source edit mode), when count limit is reached, cursor looses correct position

Expected behavior:
 - in rich text mode (not source edit mode), when count limit is reached, cursor must stay in his current position.

**Comment by w8tcha** [comment]
There is no way to fix this. the entire content is being replaced by the plugin via loadsnapshot in that case the cursor position can not be retrieved.
