### ISSUE TITLE
Multibyte support

### ISSUE THREAD

**Issue by JulesAchiel** [w8tcha/CKEditor-WordCount-Plugin#147]
Is there a configuration setting available to count the actual bytes instead of characters? When typing in eg Korean my counter is currently incorrectly displaying the length that will be inserted in the DB with a limit of 1000 characters.

eg, lawnmower in Korean is 잔디 깎는 기계
That is 8 characters but 20 bytes, inserting this in a DB field will take up 20 positions rather than 8 and thus causes problems.

The plugin is translated in multibyte languages as Korean and Chinese for UI purposes, but does it actually support multibyte characters in the calculation?

**Comment by w8tcha** [comment]
i added a new setting for that **countBytesAsChars**

**Comment by privin22** [comment]
$('textarea[name="Title.ExtendedMetadata.strAnnotation"]').ckeditor(
            {
                toolbarGroups: [
                    { name: "basicstyles", groups: ["basicstyles"] },
                    { name: "links", groups: ["links"] },
                    { name: "paragraph", groups: ['list', 'indent', 'blocks', 'align'] },
                    { name: "document", groups: ["mode"] },
                    { name: "colors" }
                ],
                removeButtons: "",
                extraPlugins: "wordcount,notification",
                wordcount: {
                    showParagraphs: false,
                    showWordCount: false,
                    showByteCount: true,
                    showCharCount: true,
                    countSpacesAsChars: true,
                    countBytesAsChars: true,
                    countHTML: true,
                    maxCharCount: 4000
                }
            }
);


I am making a call to ckeditor as above. "countBytesAsChars" doesnt seem to work.... I am getting character count returned not the byte count. What am I missing?
