### ISSUE TITLE
It can't add to more than one editor

### ISSUE THREAD

**Issue by carry0987** [w8tcha/CKEditor-WordCount-Plugin#153]
Here is the demo : 
https://carry0987.github.io/CKEditor-WordCount-Plugin/

You can see this plugin only work on the first editor

**Comment by w8tcha** [comment]
Yes that will not work in that case you need to instantiate every editor separately. Otherwise all editors are handled as one instance.

**Comment by carry0987** [comment]
@w8tcha  OK!

**Comment by w8tcha** [comment]
The easiest way would be via the editor id

https://codepen.io/w8tcha/pen/wvjwadq

**Comment by nikhilgoswami** [comment]
I don't have id on my textarea I only have classname

**Comment by w8tcha** [comment]
If you want to use a different editor config on each textarea then you need to have an id

**Comment by nikhilgoswami** [comment]
@w8tcha Adding random unique id fixed my issue
