### ISSUE TITLE
Register your package at packagist.org to make it available through composer

### ISSUE THREAD

**Issue by josefglatz** [w8tcha/CKEditor-WordCount-Plugin#162]
Hi,

thanks for adding the composer.json with #150.

It would be very nice, if you can add the repo to packagist.org. There you can also setup automatic updates after you've released/tagged a new version. https://packagist.org/

If you need help, ping me!

**Comment by w8tcha** [comment]
What do i need to publish it on that page?  Feel free to publish the plugin

**Comment by josefglatz** [comment]
Hey, Yeah I can publish it for you. But unfortunately you need to add a webhook, so that packagist.org get's updated after you push a new tag/commit/branch to your repo.

Roughly said, there are 3 steps:

1. Create a user at packagist.org
2. Submit the package (you just need the github url)
3. Set up the webhook for this package at packagist-repo ↔ github repo

Of course, I can register it, but it makes more sense of you just set up it once by your own. Once the webhook is working correctly, (there is a nice documentation available) all should work as expected :-)

**Comment by w8tcha** [comment]
package is online https://packagist.org/packages/w8tcha/ckeditor-wordcount-plugin

**Comment by josefglatz** [comment]
@w8tcha NICE!!! many many thanks!
