### ISSUE TITLE
How can i query this plug-in for the current word count.

### ISSUE THREAD

**Issue by iamkobold** [w8tcha/CKEditor-WordCount-Plugin#164]
Using some form validation; we are using a large text field (CKEditor) and we want to require a minimum number of words. I am not seeing anything obvious as to how to query what the current word/paragraph count actually is. 

Thanks in advance.

**Comment by w8tcha** [comment]
I added it in 1.17.3 you can now get the count from editorId.wordCount.wordCount and editorId.wordCount.charChount and editorId.wordCount.paragraphs

**Comment by TheSachin** [comment]
I think this should be added to documentation.

**Comment by w8tcha** [comment]
done

**Comment by doanminhtien** [comment]
Hi @w8tcha, I couldn't find 1.17.3.
I'm not able to query CKEDITOR.instances.ckeditor_id.wordCount.wordCount in 1.17.2
Please remind me if I miss something

**Comment by w8tcha** [comment]
Looks like i didn't publish the 1.17.3 yet. This version is now out via github under releases and on the ckeditor website.
