### ISSUE TITLE
Character count not updating after paste

### ISSUE THREAD

**Issue by mifas** [w8tcha/CKEditor-WordCount-Plugin#182]
Right after when you paste, then after you type a letter, the count doesn't reflect.

Reference:

![ckeditor](https://user-images.githubusercontent.com/4384874/51093401-11c7dc00-17de-11e9-9afb-76de5d2659b7.gif)

**Comment by w8tcha** [comment]
I think this was already fixed. But the demo version was not updated. It should work now!
