### ISSUE TITLE
Is there a way to just warn but not limit based on maxWordCount/maxCharCount ?

### ISSUE THREAD

**Issue by cpmangukiya** [w8tcha/CKEditor-WordCount-Plugin#183]
Hi,

This is incredible plugin and my users just liked it. Although they have specific cases where they want to just warn user with red message that limit has exceeded with so and so count. But it should not restrict user from entering more text to field. Is there a way to configure this ? If not by any chance can it be provided ? 

For an instance I have modified some of the plugin code and paste logic in my local system which works. But if it can be provided as part of controllable feature as some additional configs such as maxWordCount/maxCharCount then it will be great. I would be happy if I can become a help. 

Thanks.

**Comment by w8tcha** [comment]
i added an option. would that be enough?

**Comment by ChintanMangukiya-OUP2** [comment]
Thanks Ingo. I will check this out. 👍

**Comment by ChintanMangukiya-OUP2** [comment]
Hi Ingo, Although this plugin works when typing text beyond limits. But when I copy paste text more than the limit I is not allowing to paste beyond limit and it also shows some message which doesn't look as good. Can you please check what can be done about it ?

![image](https://user-images.githubusercontent.com/44566022/53156175-a7614300-35b6-11e9-9516-b82d32866e61.png)

**Comment by ChintanMangukiya-OUP2** [comment]
Hi Ingo, Replacing below works for me. I guess that should work.

Before:
if (config.maxWordCount > 0 || config.maxCharCount > 0 || config.maxParagraphs > 0) {

After:
if (!config.warnOnLimitOnly && (config.maxWordCount > 0 || config.maxCharCount > 0 || config.maxParagraphs > 0)) {

**Comment by w8tcha** [comment]
> Hi Ingo, Although this plugin works when typing text beyond limits. But when I copy paste text more than the limit I is not allowing to paste beyond limit and it also shows some message which doesn't look as good. Can you please check what can be done about it ?

Are you using the latest version of the kama skin? looks like its not up do date!

**Comment by w8tcha** [comment]
> Hi Ingo, Replacing below works for me. I guess that should work.

I applied the fix

**Comment by ChintanMangukiya-OUP2** [comment]
This serves the purpose. Thank you.
