### ISSUE TITLE
when first reading, wordCount-Plugin count is wrong!

### ISSUE THREAD

**Issue by takushi-k** [w8tcha/CKEditor-WordCount-Plugin#185]
1. 
<pre>
CKEDITOR.on('instanceReady', function(ev) {
ev.editor.dataProcessor.writer.selfClosingEnd = '/>';
 });
</pre>

by 1, when first reading, ckeditor translate as below.
&lt;hr /&gt;  ->  &lt;hr/&gt; 

2.
but wordCount-Plugin do not catch this event.
therefore wordCount-Plugin display "count : 6".
I expect "count : 5"

---

I think, wordCount-Plugin can not catch this event. 
therefore as below, should I add "change event fire"?

<pre>
CKEDITOR.on('instanceReady', function(ev) {
ev.editor.dataProcessor.writer.selfClosingEnd = '/>';
ev.editor.fire("change")
 });
</pre>

**Comment by w8tcha** [comment]
i dont really understand the problem. can you describe the steps to reproduce the problem?

**Comment by takushi-k** [comment]
sorry, Please confirm.
I describe the steps to reproduce. 

1.  
- index.html

<script src="ckeditor/ckeditor.js"></script>
<textarea class="ckeditor" id="ckeditorArea">&lt;hr/&gt;</textarea>


- ckeditor/config.js

CKEDITOR.editorConfig = function( config ) {

config.extraPlugins = ',wordcount';
config.wordcount = {

  // Whether or not you want to show the Paragraphs Count

  showParagraphs: false,

  // Whether or not you want to show the Word Count

  showWordCount: false,

  // Whether or not you want to show the Char Count

  showCharCount: true,

  // Whether or not you want to count Spaces as Chars

  countSpacesAsChars: true,

  // Whether or not to include Html chars in the Char Count

  countHTML: true,

  // Maximum allowed Word Count, -1 is default for unlimited

  maxWordCount: -1,

  // Maximum allowed Char Count, -1 is default for unlimited

  maxCharCount: -1,

};

CKEDITOR.on('instanceReady', function(ev) {
  // XHTML,XHTML5: ' />'
  // HTML4,HTML5: '>'
  ev.editor.dataProcessor.writer.selfClosingEnd = '/>';
});

};

---

2. index.html open
-> display count:6

---

3. source mode change
-> display count:5

**Comment by w8tcha** [comment]
Yes i can confirm. But you are right adding 

 ev.editor.fire("change");

fixes the problem

**Comment by takushi-k** [comment]
Thank you.
I was relieved to confirm that your opinion was the same as me.
