### ISSUE TITLE
Byte count

### ISSUE THREAD

**Issue by privin22** [w8tcha/CKEditor-WordCount-Plugin#186]
$('textarea[name="data.strAnnotation"]').ckeditor(
{
toolbarGroups: [
{ name: "basicstyles", groups: ["basicstyles"] },
{ name: "links", groups: ["links"] },
{ name: "paragraph", groups: ['list', 'indent', 'blocks', 'align'] },
{ name: "document", groups: ["mode"] },
{ name: "colors" }
],
removeButtons: "",
extraPlugins: "wordcount,notification",
wordcount: {
showParagraphs: false,
showWordCount: false,
showByteCount: true,
showCharCount: true,
countSpacesAsChars: true,
countBytesAsChars: true,
countHTML: true,
maxCharCount: 4000
}
}
);

I am making a call to ckeditor as above. "countBytesAsChars" doesnt seem to work.... I am getting character count returned not the byte count. What am I missing?

**Comment by w8tcha** [comment]
Should be fixed now. **CountBytesAsChars** was not working when **countHTML** was enabled

**Comment by privin22** [comment]
Thanks! When will this fix be released?

**Comment by w8tcha** [comment]
version has been released
