### ISSUE TITLE
Incorrect wordcount due to random linebreak inserted 

### ISSUE THREAD

**Issue by zhaseo1** [w8tcha/CKEditor-WordCount-Plugin#187]
Hi,

The wordcount will randomly increases when reenter the page with ckeditor after saving action due to linebreaks (could be more than one), inserted at the end of the paragraph tags. However, I already set the writter rules on instanceReady event but still the linebreak will be added.

CKEDITOR.on('instanceReady', evt => {
evt.editor.dataProcessor.writer.setRules('p',  {
      indent : false,
      breakBeforeOpen : false,
      breakAfterOpen : false,
      breakBeforeClose : false,
      breakAfterClose : false // I suppose this should fixed it but linebreaks still happen
  });
});

Is it the writter rules have to be set in other due to the plugin override it? Or is there any other ways to prevent the linebreak added or maybe showing the wordcount without the linebreak.

**Comment by w8tcha** [comment]
Can you describe the steps to reproduce the problem, and also post the config you are using?

**Comment by zhaseo1** [comment]
1. Navigate to the create record page.
2. Enter the data into the ckeditor and press save. For eg, "abcdefg". wordcount is 7 for now.
3. Navigate out of the page.
4. Navigate to the edit page of the previous saved data.
5. The wordcount is 7 or more due to linebreaks added in.

config: {
extraPlugins: 'wordcount',
wordcount: {
countHTML: true,
countSpacesAsChars: true,
maxCharCount: 100,
showCharCount: true,
}

**Comment by w8tcha** [comment]
And without the plugin the error didn’t occur?

**Comment by w8tcha** [comment]
Any update?
