### ISSUE TITLE
wordcount and sharedspaces plugins 

### ISSUE THREAD

**Issue by christinetlse** [w8tcha/CKEditor-WordCount-Plugin#188]
hello,
your plugin is fine and functions well. But it seems not to function with the plugin sharedspaces. this is my code, thank you very much for your help
`CKEDITOR.replace('texte-nouvelle',{
wordcount: {
showParagraphs: false,
showWordCount: false,
showCharCount: true,
countSpacesAsChars:true,
countHTML:false,
maxWordCount: -1,
maxCharCount: 2000
},
width : '600px',
height : '1800px',
toolbar : 'MyToolbar_user',
contentsCss : 'body {overflow:hidden;}',

extraPlugins: 'sharedspace',
sharedSpaces: {
// Configure the editor instance to place the toolbar in the div id='top'.
top: 'top',

}});`

**Comment by w8tcha** [comment]
What exactly is the problem? does it show the wrong count?. You didn't add the plugin

it should be ...
`extraPlugins: 'sharedspace,wordcount',`

**Comment by christinetlse** [comment]
Perfect!!!!
It functions ! Thank you very much ! I'm student, so not very good in js.
Thanks a lot
