### ISSUE TITLE
HIghtlight then paste error

### ISSUE THREAD

**Issue by anthropos9** [w8tcha/CKEditor-WordCount-Plugin#189]
If I highlight all the text in an editor then paste into it, wordcount seems to just add the words being pasted rather than subtract the words being replaced, thus resulting in an over limit error. Is there a way to make wordcount wait for the paste event to finish before counting the words?

**Comment by w8tcha** [comment]
Atleast with the latest version i cant reproduce the problem. I selected all text then copy and paste it and it shows the correct count. Are you using the latest version?

**Comment by anthropos9** [comment]
I was using the version that I downloaded directly from the CKE site, but just downloaded v1.17.6 and I'm still getting the error. 

Here is my config maybe I'm doing it wrong:
`config.wordcount = {
    maxCharCount: 750,
    showParagraphs: false,
    showCharCount: true,
    showWordCount: false,
    countSpacesAsChars: false,
};`

**Comment by w8tcha** [comment]
And which editor version you are using? i tested the same config with CKEditor 4.12.1 under Chrome. It works as expected.

**Comment by anthropos9** [comment]
I'm use CKE 4.12.1. I'm seeing it in FireFox 69.0b10 and Chromium 76.0.3809.87

**Comment by w8tcha** [comment]
Can you reproduce the issue on the demo page?

http://w8tcha.github.io/CKEditor-WordCount-Plugin/

also can you post your complete editor config?

**Comment by anthropos9** [comment]
Yes...
![error](https://user-images.githubusercontent.com/3867685/62627393-2ab0ef80-b8de-11e9-906c-2e54369518dc.png)

Here's my config:
```
/**
 * @license Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

CKEDITOR.editorConfig = function( config ) {
    // Define changes to default configuration here.
    // For complete reference see:
    // https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html
    config.extraPlugins = 'wordcount,notification,sourcearea,stylesheetparser,ckshortcodes';
    config.skin = 'office2013';
    // The toolbar groups arrangement, optimized for two toolbar rows.
    config.toolbarGroups = [
        { name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
        { name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
        { name: 'links' },
        { name: 'insert' },
        { name: 'forms' },
        { name: 'tools' },
        { name: 'document',    groups: [ 'mode', 'document', 'doctools' ] },
        { name: 'others' },
        '/',
        { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
        { name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'ckshortcodes' ] },
        // { name: 'styles' },
        { name: 'colors' } //,
        // { name: 'about' }
    ];

    // Remove some buttons provided by the standard plugins, which are
    // not needed in the Standard(s) toolbar.
    config.removeButtons = 'Underline,Subscript,Superscript,Table,BGColor,Image,Anchor';

    // Set the most common block elements.
    config.format_tags = 'p;h1;h2;h3;pre';

    // Simplify the dialog windows.
    config.removeDialogTabs = 'image:advanced;link:advanced';
    config.disableNativeSpellChecker = false;
    // Dialog windows are also simplified.
    config.removeDialogTabs = 'link:advanced';
    config.allowedContent = true;
    config.contentsCss = '/js/ckeditor/cke.css';
    config.wordcount = {
        maxCharCount: 750,
        showParagraphs: false,
        showCharCount: true,
        showWordCount: false,
        countSpacesAsChars: false,
    };

};
```

**Comment by w8tcha** [comment]
Maybe its a missunderstanding can you describe the exact steps to reproduce the problem?

What i did .

- select the entire text like in the demo. (Count shows 41) 
- then i hit Ctrl+c to copy
- and ctrl+v to paste
- count still shows 41 chars

**Comment by anthropos9** [comment]
Yeah it's a misunderstanding.

Here's my issue:
* select the entire text (count shows 725 is limited to 750)
* paste text with 30 
* error happens.

My working theory is that the count happens before the replacement. So wordcount counts 755, even though the end result will be 30.

**Comment by anthropos9** [comment]
@w8tcha I just submitted a pull request that fixes the issue for me.

**Comment by w8tcha** [comment]
Okay perfect. Looks good to me!

**Comment by anthropos9** [comment]
Thanks! I may work on it some more, thinking about replacing highlighted text that isn't the whole text area. Nonetheless, thank you for the merge.
