### ISSUE TITLE
No or incorrect translation in Korean, Chinese (Traditional and Simplified)

### ISSUE THREAD

**Issue by JulesAchiel** [w8tcha/CKEditor-WordCount-Plugin#191]
There is no or incorrect translation in Korean, Simplified Chinese or Simplified Chinese for the string
CharCountRemaining

Please add the translation for those language files.

ko.js 
Currently : CharCountRemaining: '남은 글자'
Requested: CharCountRemaining: '자 남음'

zn.js
CharCountRemaining entry is missing
Requested : CharCountRemaining: '個剩餘字元'

zn-cn.js
CharCountRemaining entry is missing
Requested : CharCountRemaining: '个剩余字符'

**Comment by w8tcha** [comment]
Thanks. Could you also translate the other missing chinese strings? 

WordCountRemaining: 'Words remaining',
CharCountWithHTMLRemaining: 'Characters (with HTML) remaining',
