### ISSUE TITLE
Warning for pasting more than max char limit is different in empty document

### ISSUE THREAD

**Issue by brunis** [w8tcha/CKEditor-WordCount-Plugin#196]
Plugin alerts about errors, if you try to paste past the char limit, it shows differently when the document is empty and when it already has text.
In an empty document, it will just turn the char limit counter red, in a document with some text, it will actually show the notification warning.

**Comment by w8tcha** [comment]
Can you describe the exact steps to reproduce the problem? Also what wordcount config you use.

At the moment i can't reproduce the issue.

**Comment by brunis** [comment]
If you try to paste eg. a 10k char text into an empty editor with 9k char limit (incl. whitespace etc.). you wont get a notification, document will just stay empty with counters turning red in the statusbar. If you paste the same into an editor with just one word (eg. non-empty), you'll now get the notification warning.
I will get the latest version and confirm this is still a problem.

**Comment by w8tcha** [comment]
Any update on this? tested in chrome and edge but still seems to work

<img width="595" alt="wordcount" src="https://user-images.githubusercontent.com/722575/69495125-ce410280-0ec3-11ea-9a8b-c57eb6dd51ec.PNG">

whats your editor (wordcount) config?
