### ISSUE TITLE
current word count word exceeds  limit while typing very fast

### ISSUE THREAD

**Issue by Rowdy96** [w8tcha/CKEditor-WordCount-Plugin#198]
While typing something very fast then current word count sometimes exceeds word limit and allow to write words more than word limit and current word count does not reflect at that time when we keep a pause then its reflects.
![Screenshot (38)](https://user-images.githubusercontent.com/41086823/73169454-1c6fbd80-4122-11ea-8dd7-1f622c52f3ae.png)

**Comment by w8tcha** [comment]
That's the normal behavior, there is a little delay.
