### ISSUE TITLE
Inline images are loaded on every invocation

### ISSUE THREAD

**Issue by bobvandevijver** [w8tcha/CKEditor-WordCount-Plugin#201]
Looks like this line

https://github.com/w8tcha/CKEditor-WordCount-Plugin/blob/fbd8c580837032ce1ba9cf2a96660a1e89ce033a/wordcount/plugin.js#L181

triggers a complete image load when an image is inlined in the editor. I'm not sure whether this would a browser bug or not, but at least it is known here.

The problem does not happen when only the char count is enabled, as then the "html" string set in the element does not contain valid html img tags.

**Comment by w8tcha** [comment]
Can you describe the steps to reproduce the issue?!

**Comment by bobvandevijver** [comment]
Your demo page unfortunately does not allow for image inclusion, but just embed an image in the editor and start typing while having the network debugger opened in the latest Chrome. Every char count update you will see a related image request.

**Comment by w8tcha** [comment]
> Your demo page unfortunately does not allow for image inclusion

Okay and how do i do that? i dont know what inline image is

**Comment by bobvandevijver** [comment]
See https://ckeditor.com/ckeditor-4/demo/#article, you can see the image which is inlined in the editor.

**Comment by w8tcha** [comment]
I updated the demo page inlucuding an image and the image dialog. Can you now describe the steps to reproduce the issue?

**Comment by bobvandevijver** [comment]
Just start typing, having the debug network tools opened. Every keystroke (when you have enough time between them) will trigger two image loads. I've attached a video demonstrating it.

[recording.zip](https://github.com/w8tcha/CKEditor-WordCount-Plugin/files/4729281/recording.zip)

**Comment by w8tcha** [comment]
i can see in the video, that in your debugger tools **Disable Cache** is enabled. by default this is not enabled. and the issue only occurs if the cache is disabled.

**Comment by bobvandevijver** [comment]
I could have mentioned that cache needs to be disabled, but it doesn't really matter for the issue. Browser cache is just a workaround: it completely depends on whether the image is even allowed to be cached by the browser. If, for example, the image requires validation, the server will tell the browser explicitly to not cache it, and you'll still end up triggering this behavior.

**Comment by w8tcha** [comment]
At this point i dont think there is a workaround or fix for the issue
