### ISSUE TITLE
Character limit in Source Mode not functioning

### ISSUE THREAD

**Issue by misagh-k** [w8tcha/CKEditor-WordCount-Plugin#204]
When you click on "source" button you can go over the character limit. Is it possible to limit number of characters under the source mode? I need to prevent users from going over the limit even in source mode.

**Comment by w8tcha** [comment]
The Problem is that the undo manager is not available in source mode.  The only option would be to use the CodeMirro Source (Plugin).  I commit the updated plugin. if codemirror is detected as source then the limit functions works correctly
