### ISSUE TITLE
Wordcount plugin does not update the char counter on afterPage event

### ISSUE THREAD

**Issue by iliasmertzanos** [w8tcha/CKEditor-WordCount-Plugin#211]
Hi guys,

great job you have done!

I am having an issue with events in regard to wordcount plugin.

I am trying to catch the afterPaste event (ctrl+V) but at that moment the counter evt.editor.wordcount.charCount is empty.

I tried to set a timeout, so that the read of the worcount value waits a bit and it works.
That means somehow wordcount is updating his content at some point later.

Is there any specific Event from the wordcount plugin ?

**Comment by w8tcha** [comment]
Yes you need to set the the same timeout 100 as the plugin does.

`CKEDITOR.instances.editor1.on('afterPaste', function (event) {
    console.log(event.editor.wordCount.charCount) 
}, null,null,100);`

this should work

**Comment by iliasmertzanos** [comment]
If I am getting this right there should be en event that we can bind without using timeouts. Timeouts can bring all lot of problems. 
So the question is whats the problem ? Is this a bug in CKEditor or in Wordcount?

**Comment by w8tcha** [comment]
I thinks this is a misunderstand. The Value 100 is not a timeout event. its the execution priority...

> The listener priority. Lower priority listeners are called first. Listeners with the same priority value are called in registration order.

**Comment by w8tcha** [comment]
If the value 100 is a problem for you i could remove it.

**Comment by iliasmertzanos** [comment]
Oh ok now I get it. But still I would expect that afterPaste should catch the right result from wordcount. 
So I would say somehow there is a bug in CKEditor. Why would you need the priority if it would function correctly?

**Comment by w8tcha** [comment]
Why is this a bug i dont unterstand. The default value is 10. i set it to 100 to make sure that the events of the editor are executed before the content is filtered. Otherwise its possible that the counting is wrong
