### ISSUE TITLE
Doesn't count characters of type math ( plugin "ckeditor_wiris")

### ISSUE THREAD

**Issue by rohan750** [w8tcha/CKEditor-WordCount-Plugin#213]
![Screenshot 2021-08-25 at 3 52 35 PM](https://user-images.githubusercontent.com/26869584/130774149-94e637b7-5e52-4497-946c-21e7d0c45afd.png)

**Comment by w8tcha** [comment]
There doesnt seem to be an option to support this plugin. The MathJax plugin seems is much better and works with the wordcount plugin.

At this point the crappy plugin will not supported.
