### ISSUE TITLE
Can't get it work

### ISSUE THREAD

**Issue by demo360o2** [w8tcha/CKEditor-WordCount-Plugin#215]
Hi,
 I need help configuring your plugins in a rails 6 project.
 
 I have everything configured but nothing show up. I'm a little bit confuse about that. The only thing i'm not sure with is how it should be in the html. I havn't found  exemple.

Thanks

Denis

**Comment by w8tcha** [comment]
The samples are here...

https://github.com/w8tcha/CKEditor-WordCount-Plugin/tree/master/wordcount/samples

I don't know how can I help you otherwise.

**Comment by demo360o2** [comment]
update, now I saw the script tag in my page, but the word count is not showing. When the plugin.js should be load? after page load or before?

**Comment by w8tcha** [comment]
You don't need to manually load the plugin.js. This won't work. The plugin is loaded via the editor. But you need to enable the plugin in the editor config!

Where did you configure the editor config, via the config.js?

**Comment by demo360o2** [comment]
ok good  here is my config file

`console.log('In the config.js file');
if (typeof(CKEDITOR) != 'undefined') {

    CKEDITOR.editorConfig = function( config ) {
        config.language = "fr";

        config.toolbar_mini = [
            {
                name: 'paragraph',
                groups: ['list', 'indent', 'blocks', 'align', 'bidi'],
                items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
            },
            { name: 'styles', items: ['Font', 'FontSize']},
            { name: 'colors', items: ['TextColor', 'BGColor']},
            {
                name: 'basicstyles',
                groups: ['basicstyles', 'cleanup'],
                items : ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']
            },
            { name: 'insert', items: ['Image', 'Table', 'HorizontalRule', 'SpecialChar']}
        ];

        config.extraPlugins = 'wordcount,notification';

        config.wordcount = {
            showWordCount: true,
            showCharCount: false,
            maxWordCount: 500,
        }
    }
}
`

at it is loaded in app/javascript/packs/application.js with the following line

`require("ckeditor/config")`

**Comment by w8tcha** [comment]
Config file seems correct. I assume the wordcound folder also exist in the plugin folder?

Otherwise I can't help more.

**Comment by demo360o2** [comment]
Yes it is

**Comment by w8tcha** [comment]
Did the browser error console show any errors?

**Comment by demo360o2** [comment]
No I have no error in the console

**Comment by demo360o2** [comment]
In the wordcount plugin.js,  where could I put some console.log() to trace that this file is doing is job ?

**Comment by w8tcha** [comment]
First you should check in the generated Dom if the plugin.js is actually loaded

**Comment by demo360o2** [comment]
Hi, I don't see any traces of the plugin in the html page.

**Comment by w8tcha** [comment]
Well then the config file is overridden somewhere else or plugins needs to be loaded differently in rails.

I would need some sample files or instructions on how to setup a test site to reproduce the issue. Otherwise I can't help

**Comment by demo360o2** [comment]
Hi,
 I thinks that config file is not overridden as my ckeditor load with the good custom toolbar. For the plugin have you any clue about how to test if they are properly loaded?

Thanks

**Comment by w8tcha** [comment]
Well it's possible that in your application special setup is required. I don't know how to setup a custom plugin In your application. 

I also didn't find a any documentation.

I would need the same test setup to provide help.

Also which editor version are you using?

Optionally you could also use the online builder to download the ckeditor with the word count plugin embedded.

**Comment by demo360o2** [comment]
I continue my investiguation and in fact the config.js file in the source tab of the inspector is not the one expected... So I have made some modification and now it works. I only have an issue with the css file of wordcount that is not found.

Thanks for your help
