### ISSUE TITLE
How to Add New Font Helvetica in Font Dropdown in CkEditor Standard Version 4.16.1

### ISSUE THREAD

**Issue by sridharravva** [w8tcha/CKEditor-WordCount-Plugin#223]
I am trying to add the new font family "**Helvetica**" in the Font dropdown in CkEditor Standard Package Version 4.16.1.
I have tried adding this "**Helvetica**" font to the Font dropdown but the selected text using this font "Helvetica" does not get applied with effect of this font to the selected text. Instead it simply shows the Arial font or nothing happens for the selected text. I am not sure if this is something bug with CKEditor or if I am missing anything over here.
Here it is the sample code that I have added "**Helvetica**" to the font plugin.js file.
Please let me know how to add this font to the Font dropdown. Thanks!

\ckeditor\plugins\font\plugin.js

CKEDITOR.config.font_names = 'Arial/Arial, Helvetica, sans-serif;' +
	'Helvetica;' +
	'Comic Sans MS/Comic Sans MS, cursive;' +
	'Courier New/Courier New, Courier, monospace;' +
	'Georgia/Georgia, serif;' +
	'Lucida Sans Unicode/Lucida Sans Unicode, Lucida Grande, sans-serif;' +
	'Tahoma/Tahoma, Geneva, sans-serif;' +
	'Times New Roman/Times New Roman, Times, serif;' +
	'Trebuchet MS/Trebuchet MS, Helvetica, sans-serif;' +
	'Verdana/Verdana, Geneva, sans-serif';

**Comment by w8tcha** [comment]
How is this related to the word count plugib

**Comment by sridharravva** [comment]
I know this is not related to word count plugin, but could you plz direct me to correct dev forum for this issue that I am having while adding new Font Helvetica in Font Dropdown in CkEditor Standard Version 4.16.1. Thanks!

**Comment by w8tcha** [comment]
Use the ckeditor issue tracker. Or post your question on stackoverflow.com
