### ISSUE TITLE
Complete lang fr.js

### ISSUE THREAD

**Issue by KojoEnch** [w8tcha/CKEditor-WordCount-Plugin#225]
At the moment french translation is incomplete, leading to _undefined_ strings displayed to end-users. 

Please find attached a completed one : [fr.txt](https://github.com/w8tcha/CKEditor-WordCount-Plugin/files/7313466/fr.txt)
Edit: I'll open a PR tomorrow instead ...
I would be glad if you could commit it soon, since I'm using it in Drupal setups and can't find a way to [override the external file](https://drupal.stackexchange.com/questions/307544/how-do-i-override-libraries-ckeditor-wordcount-plugin-lang-some-js)

Thank you !

**Comment by w8tcha** [comment]
I Dont understand.

**Comment by KojoEnch** [comment]
My bad you're right. The reason of my mistake is I blindly followed the Drupal module documentation to install the library, instead of checking version. And it refers to the previous tag, 1.17.8 which is missing some translation keys.

Closing with apologies. Thanks for your reactivity !
