### ISSUE TITLE
ckeditor-wordcount-plugin npm packge version update

### ISSUE THREAD

**Issue by verzion2k** [w8tcha/CKEditor-WordCount-Plugin#230]
https://www.npmjs.com/package/ckeditor-wordcount-plugin

Is this npm package is based on this repository? If so is it possible to update the npm packge to the latest master version? Thank you for your answer in advance!

**Comment by w8tcha** [comment]
done!

**Comment by verzion2k** [comment]
Thank you so much! I'll close this then.
