### ISSUE TITLE
warnOnLimitOnly set to true not removing excess characters above the limit

### ISSUE THREAD

**Issue by g1ngerninja** [w8tcha/CKEditor-WordCount-Plugin#235]
When setting warnOnLimitOnly to true as per the comments I was expecting the excess characters beyond the maxWordCount to be cut when pasting content.  However this isn't the case and you end up with all characters and a negative char counter in red.

`// Whether or not to to Warn only When limit is reached. Otherwise content above the limit will be deleted on paste or entering
    warnOnLimitOnly: false,`

Disabling pasting content larger than the maxWordCount when hardLimit is true shows a message and prevents content being pasted but I'd rather have the content pasted and cut down.

I'm running the latest version 1.17.10 and have the following options set :-

            // Default Config
            var defaultConfig = {
                showRemaining: true,
                showParagraphs: false,
                showWordCount: false,
                showCharCount: true,
                countBytesAsChars: false,
                countSpacesAsChars: true,
                countHTML: false,
                countLineBreaks: true,
                hardLimit: false,
                warnOnLimitOnly: true,
                wordDelims: '',

                //MAXLENGTH Properties
                maxWordCount: -1,
                maxCharCount: 3500,
                maxParagraphs: -1,

**Comment by w8tcha** [comment]
I don't understand the problem. The option warnOnLimitOnly means warn on limit only. Of course if you set it to true, then it will not remove any content. That's the purpose of the setting.

**Comment by g1ngerninja** [comment]
Hi,

Sorry but the comment on the option clearly states "Otherwise content above the limit will be deleted on paste or entering" which doesn't happen.  I'm fairly sure I tried with both hardlimit and warnOnLimitOnly enabled  but it didn't do anything different.  I'll try again and revert.

**Comment by w8tcha** [comment]
> Sorry but the comment on the option clearly states "Otherwise content above the limit will be deleted on paste or entering" which doesn't happen.

Then you misunderstand it. it says when set to true it only warns otherwise content is wrong. You need to set it to false and hardlimit to true.

**Comment by g1ngerninja** [comment]
If you set hardlimit to true and warnOnLimitOnly to false you can't paste anything as you get a message stating you are over the limit.  What I was expecting was to get the paste but for the paste to have been shorted to fit the limit as per how a standard textarea works.  Have I missed something?

**Comment by w8tcha** [comment]
> If you set hardlimit to true and warnOnLimitOnly to false you can't paste anything as you get a message stating you are over the limit

That is correct. thats what the description in the settings said "Otherwise content above the limit will be deleted on paste or entering".

**Comment by g1ngerninja** [comment]
OK that wording is a little misleading and should probably be rewritten.  My interpretation of that wording is, say I have a limit of 100 and try to paste 150, 100 would be entered and everything above the limit will be deleted, so the extra 50.  Are we saying we cannot configure this to work the same as a textarea?  Shame since that's exactly what I need.  We are trying to replace standard textarea with CKEditor and we need this ability, character count and forceful restriction of characters.

**Comment by w8tcha** [comment]
At this point its not possible, with the plugin it would require a large rewrite of the plugin. The problem is that the content has to be filtered. Rejecting the entire content is the better solution.

**Comment by g1ngerninja** [comment]
OK thanks, I might try editing the plugin myself and see if I can get it to do what I need.  Thanks
