### ISSUE TITLE
How to integrate wordcount plugin with ckeditor4-angular?

### ISSUE THREAD

**Issue by Rockenstien** [w8tcha/CKEditor-WordCount-Plugin#239]
I am trying to use the word count plugin in ckeditor4-angular, but not able to do it. Can you also include the sample for angular?

**Comment by w8tcha** [comment]
Can you also include the sample for angular?

No Sorry i dont know how angular works. But everything is described in the editor documentation...

https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#ckeditor-4-angular-integration-demo

reference the wordcount plugin 

  `<script src="./assets/ckeditor/plugins/wordcount/plugin.js"></script>`

and in the editor configuration add the plugin

```
<ckeditor
    data="<p>Some initial data</p>"
    [config]="{ extraPlugins: 'wordcount' }"
></ckeditor>
```
