### ISSUE TITLE
Symbol counter adds +1 to real one

### ISSUE THREAD

**Issue by Deimos715** [w8tcha/CKEditor-WordCount-Plugin#240]
Hello! I've connected Wordcount plugin to Django ckeditor and found the addition of one more symbol while testing: e.g. "test" text (4 symbols) is showed as 5 symbols in the counter (+1). Is there any way to make it correct?
![Снимок экрана от 2023-10-27 21-38-00](https://github.com/w8tcha/CKEditor-WordCount-Plugin/assets/32176134/c3b60a71-b93e-4fc6-919c-60f07821a4f1)

**Comment by w8tcha** [comment]
Are you using the latest version? atleast with 1.17.12 i can not reproduce the issue.

**Comment by Deimos715** [comment]
Yes, I've taken version 1.17.12 from development page (https://github.com/w8tcha/CKEditor-WordCount-Plugin), copied wordcount directory to /ckeditor/ckeditor/plugins and connected it in django settings this way:

'extraPlugins': ','.join(['wordcount']),
'wordcount': {
    'showWordCount': True,
    'showCharCount': True,
    'showParagraphs': True,
    'countSpacesAsChars': True,
    'countHTML': False,
    'countLineBreaks': True,
},

**Comment by w8tcha** [comment]
The line break is counted as one character if you set countLineBreaks to false then it shows the char count 4

**Comment by Deimos715** [comment]
The countLineBreaks parameter already has false value but line breaks are counted. Here's my screenshot:
![Снимок экрана от 2023-10-29 11-00-36](https://github.com/w8tcha/CKEditor-WordCount-Plugin/assets/32176134/bfbdb99e-d8db-4ab5-ace4-da49a8447677)

**Comment by w8tcha** [comment]
The screenshot shows the default config 

But as you posted above you override the config with...

'extraPlugins': ','.join(['wordcount']),
'wordcount': {
'showWordCount': True,
'showCharCount': True,
'showParagraphs': True,
'countSpacesAsChars': True,
'countHTML': False,
'countLineBreaks': True,
},

**Comment by Deimos715** [comment]
Thank you very much, it works for me now.
