### ISSUE TITLE
CKEditor-WordCount-Plugin does not with 4.2.2

### ISSUE THREAD

**Issue by teethgrinder** [w8tcha/CKEditor-WordCount-Plugin#37]
Hello , 
I am trying to make wordcount work but  it does not start working with version 4.2.2. 
I tried with version 4.1.1 , I can see wordcount but I need version 4.2.2 to work with as I have all config for my application inside it. 
here is my config added to config.js of CKEditor
    config.extraPlugins = 'wordcount,autosave';
    config.wordcount = {

```
    // Whether or not you want to show the Word Count
    showWordCount: true,

    // Whether or not you want to show the Char Count
    showCharCount: true,

    // Option to limit the characters in the Editor
    charLimit: 'unlimited',

    // Whether or not to include Html chars in the Char Count
    countHTML: false,

    // Option to limit the words in the Editor
    wordLimit: 'unlimited'
};
```

**Comment by miguelPulzo** [comment]
Amigos.. lo mismo me pasaba.. Así que me puse en la tarea de revisar los errores que arrojaba el inspector con Javascript y encontré que el problema estaba en que el ckEditor con el plugin "wordcount" está necesitando del plugin "notification".

Para solucionar el problema, descarguen y activen el plugin "notification" para poder habilitar el plugin "wordcount".

Saludos.

==========
Plugin:
http://download.ckeditor.com/notification/releases/notification_4.5.4.zip
----------
http://ckeditor.com/addon/notification
==========
