### ISSUE TITLE
Implementing a character or word count limit?

### ISSUE THREAD

**Issue by plauclair** [w8tcha/CKEditor-WordCount-Plugin#74]
Hi, I've recently started using your plugin to provide guidance to writers on the desired length of text based on the edition guidelines. I was wondering what were your thoughts on implementing a character and/or word count limiter right into the plugin? Regards, PL

**Comment by plauclair** [comment]
I have just realize there is currently a fork from @theatlantic. I'm hoping to test this soon, wish it could be merged too in the future.

**Comment by callahat** [comment]
Last I heard from the maintainer on this, the character and word count limits were to buggy and the maintainer does not intend to maintain that feature. There are forks that do this, but I doubt they will be merged.

**Comment by w8tcha** [comment]
if the forked version is working correctly i can add it if someone sends in a pull request.

**Comment by plauclair** [comment]
I'll try it soon and make changes if needed to make it work. Timeline should be by the end of January.

**Comment by mesutcakir** [comment]
What is the state ?

**Comment by plauclair** [comment]
Haven't had time to take a good look yet, but it's still on my personal roadmap.

**Comment by mesutcakir** [comment]
https://github.com/mesutcakir/CKEditor-WordCount-Plugin/tree/patch-2

I have an urgent need for this study.

**Comment by plauclair** [comment]
This is not a top priority for me right now, I have many other things on my plate.

**Comment by mesutcakir** [comment]
https://github.com/w8tcha/CKEditor-WordCount-Plugin/pull/79

![image](https://cloud.githubusercontent.com/assets/4125460/6276488/e5a1dcd6-b88f-11e4-9193-0ef53e166e2c.png)

**Comment by w8tcha** [comment]
> I have just realize there is currently a fork from @theatlantic. I'm hoping to test this soon, wish it could be merged too in the future.

That code base has it own flaws but i was able to merge the code
