### ISSUE TITLE
Respect LITE Loop Index Track Changes 

### ISSUE THREAD

**Issue by funkytraffic** [w8tcha/CKEditor-WordCount-Plugin#80]
Changes made with CKEditor plugin are not shown by wordcount.
http://ckeditor.com/addon/lite

It would be very nice to exclude some dom elements from being counted.

The best option would be something like

excludeFromCount: {'p.ice-del'} // I have not thought about the correct syntax

**Comment by mesutcakir** [comment]
I told you. I thought .
