### ISSUE TITLE
Can this do truncating if you go over a set limit (either word or char)

### ISSUE THREAD

**Issue by fredbradley** [w8tcha/CKEditor-WordCount-Plugin#83]
Can this do truncating if you go over a set limit (either word or char)?

**Comment by w8tcha** [comment]
Yes

**Comment by fredbradley** [comment]
Thank you for the ever so helpful comment!

Fortunately I figured out how to do it by finding someone with the same question on stackoverflow.

**Comment by jasonsilver** [comment]
I can't figure this out.

**Comment by fredbradley** [comment]
Hi Jason, so here's how I worked it out. 

Here is some documentation to help you: http://ckeditor.com/addon/wordcount

<b>My remarks</b>

1. You can't do it with the CDN version. You need to download the package and have it locally on your installation. 
2. Edit your config.js you need to add the 'wordcount' as an extra plugin then add the config options for the wordcount plugin. 

<b>My config.js</b>
<code>
CKEDITOR.editorConfig = function( config ) {

	config.toolbarGroups = [
		{ name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
		{ name: 'links' },
		{ name: 'insert' },
		{ name: 'forms' },
		{ name: 'tools' },
		{ name: 'document',	   groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'others' },
		'/',
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
		{ name: 'styles' },
		{ name: 'colors' },
		{ name: 'about' }
	];
	config.extraPlugins = 'wordcount';
	config.wordcount = {
		// Whether or not you want to show the Word Count
		showWordCount: true,
		
		// Whether or not you want to show the Char Count
		showCharCount: true,
		showParagraphs: true,
		countSpacesAsChars: false,

		  // Whether or not to include Html chars in the Char Count
        countHTML: false,
        //wordLimit: 10,
        //charLimit: 10
	};
	// Remove some buttons provided by the standard plugins, which are
	// not needed in the Standard(s) toolbar.
	config.removeButtons = 'Underline,Subscript,Superscript';

	// Set the most common block elements.
	config.format_tags = 'p;h1;h2;h3;pre';

	// Simplify the dialog windows.
	config.removeDialogTabs = 'image:advanced;link:advanced';
};
</code>

**Comment by w8tcha** [comment]
> I can't figure this out.

You need the latest version 1.12
then use in your config

````js
config.wordcount = {

// for word limit
   wordLimit: 10,

// for charlimit
charLimit: 50
};
````
