### ISSUE TITLE
how to reset displayed wordcount

### ISSUE THREAD

**Issue by yafp** [w8tcha/CKEditor-WordCount-Plugin#84]
hi,

i hope this is the right place to ask - haven't found a solution so far for my problem.

If i am resetting the content of my ckeditor via:
CKEDITOR.instances['editor1'].setData("");					

wordcount still displays the last valid wordcount (before my content reset). 
I would need to update it after changing the content of my editor by code.
any idea how i can do this?

**Comment by w8tcha** [comment]
Atleast with the latest version 1.12 i can not reproduce this. Can you retry with the latest version?
