### ISSUE TITLE
How to set limit of chars?

### ISSUE THREAD

**Issue by AlbertRAR** [w8tcha/CKEditor-WordCount-Plugin#85]
Hi, 
thanks for this plugin. How can we set limit of max chars? Just saw in css file (wordcount.css)  that you have class name "cke_wordcountLimitReached". So that's why i'm asking)

**Comment by w8tcha** [comment]
config.wordcount = {

   showCharCount: true,

    maxCharCount: 10
};

**Comment by AlbertRAR** [comment]
Thanks, already set:)
Btw, plugin needs to be updated in ckeditor site too, i noticed, that the version presented there seems to be outdated (v 1.10).

**Comment by w8tcha** [comment]
just updated it to version 1.12
