### ISSUE TITLE
Paragraph count doesn't work

### ISSUE THREAD

**Issue by AlbertRAR** [w8tcha/CKEditor-WordCount-Plugin#86]
Hi, again. 
Just tried to enable "Paragraphs count"  by toggling to

```javascript
showParagraphs: true
```
but it counts only the1-st paragraph.

**Comment by w8tcha** [comment]
Are you using the latest version?

**Comment by AlbertRAR** [comment]
Yep

**Comment by AlbertRAR** [comment]
http://w8tcha.github.io/CKEditor-WordCount-Plugin/ 
if you updated this files too, you can see that it is not working as expected.

**Comment by w8tcha** [comment]
it seems that it doesn't work with the standard version of the editor only if you download the full version.

But i don't know what is causing this. Must be some missing plugins

**Comment by AlbertRAR** [comment]
Tried both standart and full. It seems, that problem lies in line 168 at plugin.js (countParagraphs func). Just tried to replace regexp on line 168 with regexp on line 159, and it began to count paragraphs as chars. So the problem is in countParagraphs func regexp right?)

**Comment by w8tcha** [comment]
> So the problem is in countParagraphs func regexp right?)

No the getData function returns different data with the standard or full editor. This is caused ether by a different config or plugin

**Comment by w8tcha** [comment]
Ok turns out this requires the htmlwriter plugin, this is now required

**Comment by andradecia** [comment]
We need count the amount of shift-enter also. Thanks!
