### ISSUE TITLE
Character count not correct when counting HTML

### ISSUE THREAD

**Issue by SergiodeIsidro** [w8tcha/CKEditor-WordCount-Plugin#88]
Hi, first of all, thank you for a great plugin! I am using the latest version from the ckeditor downloader, and I have found an issue I hope you can help me with: when including HTML in the character count, it is different when the editor is enabled and disabled, and it's also a different count than the actual character count according to the console.

Enabled:

![image](https://cloud.githubusercontent.com/assets/13051397/8358267/98578c9a-1b5f-11e5-9cda-9bb650a3ce62.png)

Disabled:

![image](https://cloud.githubusercontent.com/assets/13051397/8358296/bff7b432-1b5f-11e5-9f01-8b39ac934c90.png)

**Comment by w8tcha** [comment]
Looks like when using the getData function to retrieve the content the editor adds some trailing space to the content. I'm changing it to getSnapshot to retrieve the raw content instead.
