### ISSUE TITLE
Wrong error on paste text

### ISSUE THREAD

**Issue by bubnovKelnik** [w8tcha/CKEditor-WordCount-Plugin#91]
After Paste I got error about limits
In my config I set 
showWordCount: false,

In source code I see:
editor.on("paste", function(event) {
   if (config.maxWordCount > 0 || config.maxCharCount > 0) {
      ...
      var wordCount = 0,
      charCount = 0,....
      ...
      if (config.showWordCount) {
         wordCount = countWords(text);
      }
      //SO because config.showWordCount is false, wordCount = 0;
      ...
      if (wordCount > config.maxWordCount) {
         notification.show();
         event.cancel();
      }
      // maxWordCount = -1 is default for unlimited
      // wordCount (0) is actually more then -1, so warning notification is fire

//Suggest to init wordCount and charCount with the same default values (-1)

**Comment by bubnovKelnik** [comment]
Also plugin gets chars count in wrong way.
On editor.on("paste") the editor has no pasted text yet. But in plugin`s I see:
if (config.countHTML) {
   return (editorInstance.getSnapshot().length);
   /// That will return text length BEFORE paste
}

Suggest change to editor.on("afterPaste")

**Comment by kamranzafar** [comment]
I was getting the same error on paste, I fixed it with this:

if (wordCount > config.maxWordCount && config.maxWordCount != -1) {
notification.show();
event.cancel();
}
