### ISSUE TITLE
Disabled copy and paste after adding wordcount plugin of Ckeditor

### ISSUE THREAD

**Issue by testjava03** [w8tcha/CKEditor-WordCount-Plugin#93]
I am using this plugin for word count. As requirment of this plugin i added plugin notification. My problem is this after adding notification plugin copy and paste via keypress got disabled and gives this in condole : 

Uncaught TypeError: CKEDITOR.tools.getUniqueId is not a function
Notification @ plugin.js?t=E4KA:121
(anonymous function) @ plugin.js?t=E4KA:360
i    @ ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13
f @ ckeditor.js:594
(anonymous function) @ ckeditor.js:599
(anonymous function) @ ckeditor.js:598

I added following code for adding plugin : 

CKEDITOR.config.extraPlugins = 'toolbar';
		CKEDITOR.config.extraPlugins = 'htmlwriter';
		CKEDITOR.config.extraPlugins = 'notification';
		CKEDITOR.config.extraPlugins = 'wordcount';
		CKEDITOR.config.wordcount = {
			    showParagraphs: true,
			    showWordCount: true,
			    showCharCount: false,
			    countSpacesAsChars: false,
			    countHTML: false,
			    maxWordCount: 10,
//			    maxCharCount: 10
		};

**Comment by w8tcha** [comment]
Check your config it should look like this....

```javascript
CKEDITOR.config.extraPlugins = 'toolbar';
CKEDITOR.config.extraPlugins = 'htmlwriter,notification,wordcount';
CKEDITOR.config.wordcount = {
showParagraphs: true,
showWordCount: true,
showCharCount: false,
countSpacesAsChars: false,
countHTML: false,
maxWordCount: 10,
// maxCharCount: 10
};
```

**Comment by katrinkump** [comment]
Is there a solution for this issue. My config has the exact same configuration as the example above. I have ckeditor version:"4.5.0", wordcount Version: 1.15, notification Version: 4.5.11. I am getting the following error:
Uncaught TypeError: CKEDITOR.tools.getUniqueId is not a function
    at Notification (plugin.js?t=E5OD:121)
    at a.<anonymous> (plugin.js?t=E5OD:383)
    at a.h (ckeditor.js:10)
    at a.CKEDITOR.event.CKEDITOR.event.fire (ckeditor.js:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
    at f (ckeditor.js:584)
    at ckeditor.js:590
    at ckeditor.js:588

**Comment by w8tcha** [comment]
Did the issue also occurs with the latest versions?

**Comment by katrinkump** [comment]
Yes it did.

**Comment by w8tcha** [comment]
You also use the latest editor 4.7.1 and the latest notification 4.7.1?

**Comment by katrinkump** [comment]
Yes I tried that too. One additional piece. What actually breaks it for me is setting either maxWordCount: or      maxCharCount: to values different than -1.

**Comment by w8tcha** [comment]
The problem is that the issue is caused by the notification plugin. So i not can really do nothing about that.
