### ISSUE TITLE
count char on copy/paste

### ISSUE THREAD

**Issue by orsopoeta** [w8tcha/CKEditor-WordCount-Plugin#94]
a found a bug in copy and paste action.
by screenshot, i copy only few characters: it's impossibile that my text is above limit.

this is my config:

	config.wordcount = {
	    showParagraphs: false,
	    showWordCount: true,
	    showCharCount: true,
	    countSpacesAsChars: false,
	    countHTML: false,
	    maxWordCount: -1,
	    maxCharCount: 255
	};

with 
maxWordCount: #positiveNumber# 
works perfect...

[look screenshot please](https://cloud.githubusercontent.com/assets/1925881/9225295/e868efc0-4108-11e5-8180-d3a483af6937.jpg)

**Comment by w8tcha** [comment]
Are you using the latest plugin.js from github? This issue should be already fixed.

**Comment by nino-s** [comment]
@w8tcha i checked out the master branch, but still the same error. 

You don't have two separate conditions, just one: `if (config.maxWordCount > 0 || config.maxCharCount > 0) {`. But on line 361 and 366 you do have two sperate. You have to check more than just the `charCount`. Below is a fix.

https://github.com/w8tcha/CKEditor-WordCount-Plugin/blob/master/wordcount/plugin.js#L361
```php
                if (config.maxCharCount > 0 && charCount > config.maxCharCount) {
                    notification.show();
                    event.cancel();
                }

                if (config.maxWordCount > 0 && wordCount > config.maxWordCount) {
                    notification.show();
                    event.cancel();
                }
```

**Comment by qmachard** [comment]
Hi, you should be modify the condition because have a bug when hardLimit is false.
```
if (config.maxCharCount > 0 && charCount > config.maxCharCount && config.hardLimit) {
    notification.show();
    event.cancel();
}
if (config.maxWordCount > 0 && wordCount > config.maxWordCount && config.hardLimit) {
    notification.show();
    event.cancel();
}
```

**Comment by jparia** [comment]
Bug :
charCount is always superior at default value of config.maxCharCount = -1
and 
wordCount  is always superior at  default value of config.maxWordCount  = -1
soluce :
var charCount, wordCount  must bee initialized to -1 in the function paste
